import test from 'node:test';
import assert from 'node:assert/strict';
import { addItem, createApi, normalizeUrl, positiveInteger, ApiError } from '../src/api.mjs';
test('URL exige HTTPS fora de desenvolvimento',()=>{assert.equal(normalizeUrl('https://example.com/'),'https://example.com');assert.throws(()=>normalizeUrl('http://example.com'));assert.equal(normalizeUrl('http://127.0.0.1:5184',true),'http://127.0.0.1:5184');assert.throws(()=>normalizeUrl('https://user:pass@example.com'));});
test('quantidades não aceitam frações ou negativos',()=>{for(const n of ['1.5','-1','0','1e2','1000001'])assert.throws(()=>positiveInteger(n));assert.equal(positiveInteger('12'),12);});
test('carrinho agrupa produtos e preserva o anterior',()=>{const before=[{produtoId:1,quantidade:2}];assert.deepEqual(addItem(before,1,3),[{produtoId:1,quantidade:5}]);assert.equal(before[0].quantidade,2);});
test('requisição envia token e mantém identificação da operação',async()=>{let sent;const body={chaveOperacao:'abc',quantidade:2};const api=createApi('https://example.com','secret',async(url,options)=>{sent={url,options};return {ok:true,status:200,json:async()=>({id:3})};});assert.deepEqual(await api('movimentacoes',{method:'POST',body}),{id:3});assert.equal(sent.options.headers.Authorization,'Bearer secret');assert.equal(sent.options.headers['X-TechPaper-Client'],'mobile');assert.deepEqual(JSON.parse(sent.options.body),body);});
test('erro 401 preserva status para expiração de sessão',async()=>{const api=createApi('https://example.com','token',async()=>({ok:false,status:401,json:async()=>({message:'Sessão expirada'})}));await assert.rejects(api('produtos'),e=>e instanceof ApiError&&e.status===401);});
test('falha de rede nunca é interpretada como gravação confirmada',async()=>{const api=createApi('https://example.com','token',async()=>{throw new TypeError('network');});await assert.rejects(api('movimentacoes',{method:'POST',body:{}}),e=>e.status===0&&e.message.includes('Sem confirmação'));});
