-- TECHPAPER PIM IV - BANCO COMPLETO POSTGRESQL/NEON
-- Execute este arquivo inteiro no SQL Editor do Neon. Pode ser executado novamente com segurança.
BEGIN;

-- ============================================================
-- 001_schema.sql
-- ============================================================
-- Banco NOVO do PIM IV para PostgreSQL/Neon. Idempotente para inicialização da API.
CREATE TABLE IF NOT EXISTS usuarios (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Name" VARCHAR(100) NOT NULL,
 "Login" VARCHAR(100) NOT NULL UNIQUE,
 "Password" VARCHAR(255) NOT NULL,
 "Role" VARCHAR(20) NOT NULL DEFAULT 'Operador',
 "Ativo" BOOLEAN NOT NULL DEFAULT TRUE,
 "TemaEscuro" BOOLEAN NOT NULL DEFAULT FALSE,
 "AvatarId" INTEGER NOT NULL DEFAULT 1,
 "AvatarSelecionado" BOOLEAN NOT NULL DEFAULT FALSE,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_usuario_perfil CHECK ("Role" IN ('Admin','Supervisor','Operador')),
 CONSTRAINT ck_usuario_avatar CHECK ("AvatarId" BETWEEN 1 AND 6)
);
-- As instruções ALTER tornam o script idempotente também em bancos já implantados.
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS "TemaEscuro" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS "AvatarId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS "AvatarSelecionado" BOOLEAN NOT NULL DEFAULT FALSE;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_usuario_avatar' AND conrelid='usuarios'::regclass) THEN
  ALTER TABLE usuarios ADD CONSTRAINT ck_usuario_avatar CHECK ("AvatarId" BETWEEN 1 AND 6);
 END IF;
END $$;
CREATE TABLE IF NOT EXISTS fornecedores (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Cnpj" VARCHAR(18) NOT NULL UNIQUE,
 "RazaoSocial" VARCHAR(150) NOT NULL,
 "NomeFantasia" VARCHAR(150) NOT NULL,
 "Segmento" VARCHAR(50) NOT NULL,
 "Telefone" VARCHAR(20) NOT NULL,
 "Email" VARCHAR(100) NOT NULL,
 "PrazoEntregaDias" INTEGER NOT NULL,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_fornecedor_prazo CHECK ("PrazoEntregaDias">=0)
);
CREATE TABLE IF NOT EXISTS produtos (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Sku" VARCHAR(50) NOT NULL UNIQUE,
 "Nome" VARCHAR(100) NOT NULL,
 "Categoria" VARCHAR(50) NOT NULL,
 "Fornecedor" VARCHAR(150) NOT NULL,
 "FornecedorId" INTEGER NULL REFERENCES fornecedores("Id"),
 "PrecoCusto" NUMERIC(18,2) NOT NULL DEFAULT 0,
 "PrecoVenda" NUMERIC(18,2) NOT NULL DEFAULT 0,
 "Estoque" INTEGER NOT NULL DEFAULT 0,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_produto_valores CHECK ("PrecoCusto">=0 AND "PrecoVenda">=0 AND "Estoque">=0)
);
CREATE INDEX IF NOT EXISTS ix_produto_nome ON produtos("Nome");
CREATE INDEX IF NOT EXISTS ix_produto_categoria ON produtos("Categoria");
CREATE INDEX IF NOT EXISTS ix_produto_estoque ON produtos("Estoque");
CREATE TABLE IF NOT EXISTS movimentacoes (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Tipo" VARCHAR(20) NOT NULL,
 "ProdutoId" INTEGER NOT NULL REFERENCES produtos("Id"),
 "ProdutoNome" VARCHAR(100) NOT NULL,
 "Quantidade" INTEGER NOT NULL,
 "Motivo" VARCHAR(100) NOT NULL,
 "Responsavel" VARCHAR(100) NOT NULL,
 "UsuarioId" VARCHAR(100) NOT NULL,
 "ResponsavelId" INTEGER NOT NULL REFERENCES usuarios("Id"),
 "ChaveOperacao" VARCHAR(36) NOT NULL UNIQUE,
 "DataHora" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_movimento_quantidade CHECK ("Quantidade">0 AND "Tipo" IN ('Entrada','Saida'))
);
CREATE INDEX IF NOT EXISTS ix_movimento_produto_data ON movimentacoes("ProdutoId","DataHora");
CREATE INDEX IF NOT EXISTS ix_movimento_data ON movimentacoes("DataHora");
CREATE INDEX IF NOT EXISTS ix_movimento_usuario_data ON movimentacoes("ResponsavelId","DataHora");
CREATE TABLE IF NOT EXISTS sessoes (
 "TokenHash" CHAR(64) PRIMARY KEY,
 "UsuarioId" INTEGER NOT NULL REFERENCES usuarios("Id") ON DELETE CASCADE,
 "ExpiraEm" TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sessao_expira ON sessoes("ExpiraEm");
CREATE TABLE IF NOT EXISTS relatos_inclusao (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Categoria" VARCHAR(30) NOT NULL,
 "Descricao" VARCHAR(2000) NOT NULL,
 "Status" VARCHAR(20) NOT NULL DEFAULT 'Recebido',
 "UsuarioId" INTEGER NOT NULL REFERENCES usuarios("Id"),
 "UsuarioNome" VARCHAR(100) NOT NULL,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "DataAtualizacao" TIMESTAMPTZ NULL,
 CONSTRAINT ck_relato_categoria CHECK ("Categoria" IN ('Discriminacao','Acessibilidade','Sugestao','Outro')),
 CONSTRAINT ck_relato_status CHECK ("Status" IN ('Recebido','EmAnalise','Concluido')),
 CONSTRAINT ck_relato_descricao CHECK (CHAR_LENGTH(TRIM("Descricao")) BETWEEN 20 AND 2000)
);
CREATE INDEX IF NOT EXISTS ix_relato_usuario_data ON relatos_inclusao("UsuarioId","DataCriacao");
CREATE INDEX IF NOT EXISTS ix_relato_status_data ON relatos_inclusao("Status","DataCriacao");
CREATE TABLE IF NOT EXISTS orcamentos (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Cliente" VARCHAR(150) NOT NULL,
 "Observacoes" VARCHAR(1000) NOT NULL DEFAULT '',
 "Status" VARCHAR(20) NOT NULL DEFAULT 'Rascunho',
 "UsuarioId" INTEGER NOT NULL REFERENCES usuarios("Id"),
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "Validade" DATE NOT NULL,
 "Total" NUMERIC(18,2) NOT NULL,
 "Versao" INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT ck_orcamento_status CHECK ("Status" IN ('Rascunho','Aprovado','Cancelado')),
 CONSTRAINT ck_orcamento_total CHECK ("Total">=0)
);
CREATE INDEX IF NOT EXISTS ix_orcamento_status_data ON orcamentos("Status","DataCriacao");
CREATE TABLE IF NOT EXISTS itens_orcamento (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "OrcamentoId" INTEGER NOT NULL REFERENCES orcamentos("Id") ON DELETE CASCADE,
 "ProdutoId" INTEGER NOT NULL REFERENCES produtos("Id"),
 "ProdutoNome" VARCHAR(100) NOT NULL,
 "Quantidade" INTEGER NOT NULL,
 "PrecoUnitario" NUMERIC(18,2) NOT NULL,
 "Subtotal" NUMERIC(18,2) NOT NULL,
 CONSTRAINT ck_item_valores CHECK ("Quantidade">0 AND "PrecoUnitario">=0 AND "Subtotal"=ROUND("Quantidade"*"PrecoUnitario",2)),
 CONSTRAINT uq_item_produto UNIQUE("OrcamentoId","ProdutoId")
);
CREATE TABLE IF NOT EXISTS auditoria_estoque (
 "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ProdutoId" INTEGER NOT NULL,
 "SaldoAnterior" INTEGER NOT NULL,
 "SaldoAtual" INTEGER NOT NULL,
 "DataHora" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_auditoria_produto_data ON auditoria_estoque("ProdutoId","DataHora");


-- ============================================================
-- 002_routines.sql
-- ============================================================
-- Funções e gatilhos PostgreSQL. Reexecutável com segurança.
CREATE OR REPLACE FUNCTION tr_produto_auditoria_fn() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
 IF OLD."Estoque"<>NEW."Estoque" THEN
  INSERT INTO auditoria_estoque("ProdutoId","SaldoAnterior","SaldoAtual","DataHora") VALUES(NEW."Id",OLD."Estoque",NEW."Estoque",CURRENT_TIMESTAMP);
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS tr_produto_auditoria ON produtos;
CREATE TRIGGER tr_produto_auditoria AFTER UPDATE ON produtos FOR EACH ROW EXECUTE PROCEDURE tr_produto_auditoria_fn();

-- Regra central de estoque: qualquer INSERT válido em movimentacoes altera o saldo
-- exatamente uma vez, inclusive quando o registro for criado fora da API.
CREATE OR REPLACE FUNCTION trg_atualiza_estoque_fn() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
 IF NEW."Tipo"='Entrada' THEN
  UPDATE produtos SET "Estoque"="Estoque"+NEW."Quantidade" WHERE "Id"=NEW."ProdutoId";
 ELSE
  UPDATE produtos SET "Estoque"="Estoque"-NEW."Quantidade"
   WHERE "Id"=NEW."ProdutoId" AND "Estoque">=NEW."Quantidade";
  IF NOT FOUND THEN RAISE EXCEPTION 'Estoque insuficiente.'; END IF;
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS "TRG_ATUALIZA_ESTOQUE" ON movimentacoes;
CREATE TRIGGER "TRG_ATUALIZA_ESTOQUE" AFTER INSERT ON movimentacoes
 FOR EACH ROW EXECUTE PROCEDURE trg_atualiza_estoque_fn();

CREATE OR REPLACE FUNCTION tr_movimento_imutavel_fn() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Histórico imutável. Registre uma movimentação compensatória.'; END $$;
DROP TRIGGER IF EXISTS tr_movimento_sem_edicao ON movimentacoes;
CREATE TRIGGER tr_movimento_sem_edicao BEFORE UPDATE ON movimentacoes FOR EACH ROW EXECUTE PROCEDURE tr_movimento_imutavel_fn();
DROP TRIGGER IF EXISTS tr_movimento_sem_exclusao ON movimentacoes;
CREATE TRIGGER tr_movimento_sem_exclusao BEFORE DELETE ON movimentacoes FOR EACH ROW EXECUTE PROCEDURE tr_movimento_imutavel_fn();

CREATE OR REPLACE FUNCTION sp_registrar_movimentacao(p_produto INTEGER,p_tipo VARCHAR,p_quantidade INTEGER,p_motivo VARCHAR,p_usuario INTEGER,p_chave VARCHAR)
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v_saldo INTEGER;v_nome VARCHAR(100);v_usuario VARCHAR(100);v_login VARCHAR(100);v_id INTEGER;v_match BOOLEAN;
BEGIN
 IF p_quantidade IS NULL OR p_quantidade<=0 OR p_quantidade>1000000 OR p_tipo IS NULL OR p_tipo NOT IN ('Entrada','Saida')
    OR p_chave IS NULL OR CHAR_LENGTH(p_chave)<>36 OR p_motivo IS NULL OR CHAR_LENGTH(TRIM(p_motivo))=0 THEN
  RAISE EXCEPTION 'Dados da movimentação inválidos.';
 END IF;
 SELECT "Estoque","Nome" INTO v_saldo,v_nome FROM produtos WHERE "Id"=p_produto FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Produto inexistente.';END IF;
 SELECT "Id",("ProdutoId"=p_produto AND "Tipo"=p_tipo AND "Quantidade"=p_quantidade AND "Motivo"=p_motivo AND "ResponsavelId"=p_usuario)
 INTO v_id,v_match FROM movimentacoes WHERE "ChaveOperacao"=p_chave;
 IF FOUND THEN
  IF NOT v_match THEN RAISE EXCEPTION 'Chave de operação já utilizada com outros dados.';END IF;
  RETURN v_id;
 END IF;
 SELECT "Name","Login" INTO v_usuario,v_login FROM usuarios WHERE "Id"=p_usuario AND "Ativo"=TRUE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Usuário inexistente ou inativo.';END IF;
 IF p_tipo='Saida' AND v_saldo<p_quantidade THEN RAISE EXCEPTION 'Estoque insuficiente.';END IF;
 -- A alteração do saldo pertence à TRG_ATUALIZA_ESTOQUE. Mantê-la fora desta
 -- função evita duplicidade e garante a mesma regra para toda origem de INSERT.
 INSERT INTO movimentacoes("Tipo","ProdutoId","ProdutoNome","Quantidade","Motivo","Responsavel","UsuarioId","ResponsavelId","ChaveOperacao","DataHora")
 VALUES(p_tipo,p_produto,v_nome,p_quantidade,p_motivo,v_usuario,v_login,p_usuario,p_chave,CURRENT_TIMESTAMP) RETURNING "Id" INTO v_id;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION sp_resumo_estoque(p_limite INTEGER)
RETURNS TABLE(id INTEGER,sku VARCHAR,nome VARCHAR,estoque INTEGER,preco_custo NUMERIC,valor_em_estoque NUMERIC)
LANGUAGE sql AS $$
 SELECT "Id","Sku","Nome","Estoque","PrecoCusto",ROUND("Estoque"*"PrecoCusto",2) FROM produtos WHERE "Estoque"<p_limite ORDER BY "Estoque","Nome"
$$;

-- Procedure administrativa real, mantida separada das funções que retornam dados.
-- Pode ser chamada por uma rotina de manutenção com: CALL sp_limpar_sessoes_expiradas();
CREATE OR REPLACE PROCEDURE sp_limpar_sessoes_expiradas()
LANGUAGE plpgsql AS $$
BEGIN
 DELETE FROM sessoes WHERE "ExpiraEm"<CURRENT_TIMESTAMP;
END $$;


-- ============================================================
-- 003_demo.sql
-- ============================================================
-- Dados fictícios idempotentes para demonstração. Não contém senhas.
INSERT INTO fornecedores("Cnpj","RazaoSocial","NomeFantasia","Segmento","Telefone","Email","PrazoEntregaDias")
VALUES('00.000.000/0001-00','Fornecedor Demonstrativo','Papel & Cia Demo','Papelaria','(11) 0000-0000','contato@example.com',5)
ON CONFLICT ("Cnpj") DO NOTHING;
INSERT INTO produtos("Sku","Nome","Categoria","Fornecedor","FornecedorId","PrecoCusto","PrecoVenda")
SELECT 'CAD-001','Caderno universitário','Cadernos',"NomeFantasia","Id",12.50,24.90 FROM fornecedores WHERE "Cnpj"='00.000.000/0001-00'
ON CONFLICT ("Sku") DO NOTHING;
INSERT INTO produtos("Sku","Nome","Categoria","Fornecedor","FornecedorId","PrecoCusto","PrecoVenda")
SELECT 'CAN-001','Caneta azul','Escrita',"NomeFantasia","Id",1.20,2.50 FROM fornecedores WHERE "Cnpj"='00.000.000/0001-00'
ON CONFLICT ("Sku") DO NOTHING;


COMMIT;
