-- Banco NOVO do PIM IV para PostgreSQL/Neon. Idempotente para inicialização da API.
CREATE TABLE IF NOT EXISTS usuarios (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Name" VARCHAR(100) NOT NULL,
 "Login" VARCHAR(100) NOT NULL UNIQUE,
 "Password" VARCHAR(255) NOT NULL,
 "Role" VARCHAR(20) NOT NULL DEFAULT 'Operador',
 "Ativo" BOOLEAN NOT NULL DEFAULT TRUE,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_usuario_perfil CHECK ("Role" IN ('Admin','Supervisor','Operador'))
);
CREATE TABLE IF NOT EXISTS fornecedores (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Cnpj" VARCHAR(18) NOT NULL UNIQUE,
 "RazaoSocial" VARCHAR(150) NOT NULL,
 "NomeFantasia" VARCHAR(150) NOT NULL,
 "Segmento" VARCHAR(50) NOT NULL,
 "Telefone" VARCHAR(20) NOT NULL,
 "Email" VARCHAR(100) NOT NULL,
 "PrazoEntregaDias" INTEGER NOT NULL,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_fornecedor_prazo CHECK ("PrazoEntregaDias">=0)
);
CREATE TABLE IF NOT EXISTS produtos (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Sku" VARCHAR(50) NOT NULL UNIQUE,
 "Nome" VARCHAR(100) NOT NULL,
 "Categoria" VARCHAR(50) NOT NULL,
 "Fornecedor" VARCHAR(150) NOT NULL,
 "FornecedorId" INTEGER NULL REFERENCES fornecedores("Id"),
 "PrecoCusto" NUMERIC(18,2) NOT NULL DEFAULT 0,
 "PrecoVenda" NUMERIC(18,2) NOT NULL DEFAULT 0,
 "Estoque" INTEGER NOT NULL DEFAULT 0,
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_produto_valores CHECK ("PrecoCusto">=0 AND "PrecoVenda">=0 AND "Estoque">=0)
);
CREATE INDEX IF NOT EXISTS ix_produto_nome ON produtos("Nome");
CREATE INDEX IF NOT EXISTS ix_produto_categoria ON produtos("Categoria");
CREATE INDEX IF NOT EXISTS ix_produto_estoque ON produtos("Estoque");
CREATE TABLE IF NOT EXISTS movimentacoes (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Tipo" VARCHAR(20) NOT NULL,
 "ProdutoId" INTEGER NOT NULL REFERENCES produtos("Id"),
 "ProdutoNome" VARCHAR(100) NOT NULL,
 "Quantidade" INTEGER NOT NULL,
 "Motivo" VARCHAR(100) NOT NULL,
 "Responsavel" VARCHAR(100) NOT NULL,
 "UsuarioId" VARCHAR(100) NOT NULL,
 "ResponsavelId" INTEGER NOT NULL REFERENCES usuarios("Id"),
 "ChaveOperacao" VARCHAR(36) NOT NULL UNIQUE,
 "DataHora" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_movimento_quantidade CHECK ("Quantidade">0 AND "Tipo" IN ('Entrada','Saida'))
);
CREATE INDEX IF NOT EXISTS ix_movimento_produto_data ON movimentacoes("ProdutoId","DataHora");
CREATE INDEX IF NOT EXISTS ix_movimento_data ON movimentacoes("DataHora");
CREATE INDEX IF NOT EXISTS ix_movimento_usuario_data ON movimentacoes("ResponsavelId","DataHora");
CREATE TABLE IF NOT EXISTS sessoes (
 "TokenHash" CHAR(64) PRIMARY KEY,
 "UsuarioId" INTEGER NOT NULL REFERENCES usuarios("Id") ON DELETE CASCADE,
 "ExpiraEm" TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sessao_expira ON sessoes("ExpiraEm");
CREATE TABLE IF NOT EXISTS orcamentos (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Cliente" VARCHAR(150) NOT NULL,
 "Observacoes" VARCHAR(1000) NOT NULL DEFAULT '',
 "Status" VARCHAR(20) NOT NULL DEFAULT 'Rascunho',
 "UsuarioId" INTEGER NOT NULL REFERENCES usuarios("Id"),
 "DataCriacao" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "Validade" DATE NOT NULL,
 "Total" NUMERIC(18,2) NOT NULL,
 "Versao" INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT ck_orcamento_status CHECK ("Status" IN ('Rascunho','Aprovado','Cancelado')),
 CONSTRAINT ck_orcamento_total CHECK ("Total">=0)
);
CREATE INDEX IF NOT EXISTS ix_orcamento_status_data ON orcamentos("Status","DataCriacao");
CREATE TABLE IF NOT EXISTS itens_orcamento (
 "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "OrcamentoId" INTEGER NOT NULL REFERENCES orcamentos("Id") ON DELETE CASCADE,
 "ProdutoId" INTEGER NOT NULL REFERENCES produtos("Id"),
 "ProdutoNome" VARCHAR(100) NOT NULL,
 "Quantidade" INTEGER NOT NULL,
 "PrecoUnitario" NUMERIC(18,2) NOT NULL,
 "Subtotal" NUMERIC(18,2) NOT NULL,
 CONSTRAINT ck_item_valores CHECK ("Quantidade">0 AND "PrecoUnitario">=0 AND "Subtotal"=ROUND("Quantidade"*"PrecoUnitario",2)),
 CONSTRAINT uq_item_produto UNIQUE("OrcamentoId","ProdutoId")
);
CREATE TABLE IF NOT EXISTS auditoria_estoque (
 "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ProdutoId" INTEGER NOT NULL,
 "SaldoAnterior" INTEGER NOT NULL,
 "SaldoAtual" INTEGER NOT NULL,
 "DataHora" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_auditoria_produto_data ON auditoria_estoque("ProdutoId","DataHora");
